// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVsa96AdXwxofqvxkPk0SNDE28XH4bzc',
    appId: '1:409693216731:web:7e7e6dc556dc44ff1351fe',
    messagingSenderId: '409693216731',
    projectId: 'agapp-9c4c5',
    authDomain: 'agapp-9c4c5.firebaseapp.com',
    storageBucket: 'agapp-9c4c5.firebasestorage.app',
    measurementId: 'G-XXTEDRSL0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-EHhJf2HILJk1y9E1KsStCUgf8SuuV4',
    appId: '1:409693216731:android:188858813c027c681351fe',
    messagingSenderId: '409693216731',
    projectId: 'agapp-9c4c5',
    storageBucket: 'agapp-9c4c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnIe_AMiVYjsx6rOfZ85uRe4UZM6aqDOk',
    appId: '1:409693216731:ios:7fbb32b4bcaedda51351fe',
    messagingSenderId: '409693216731',
    projectId: 'agapp-9c4c5',
    storageBucket: 'agapp-9c4c5.firebasestorage.app',
    iosBundleId: 'com.example.agapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnIe_AMiVYjsx6rOfZ85uRe4UZM6aqDOk',
    appId: '1:409693216731:ios:7fbb32b4bcaedda51351fe',
    messagingSenderId: '409693216731',
    projectId: 'agapp-9c4c5',
    storageBucket: 'agapp-9c4c5.firebasestorage.app',
    iosBundleId: 'com.example.agapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpVsa96AdXwxofqvxkPk0SNDE28XH4bzc',
    appId: '1:409693216731:web:ee265a2c14b2bc3c1351fe',
    messagingSenderId: '409693216731',
    projectId: 'agapp-9c4c5',
    authDomain: 'agapp-9c4c5.firebaseapp.com',
    storageBucket: 'agapp-9c4c5.firebasestorage.app',
    measurementId: 'G-ZZMX50P4VB',
  );
}
