// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-gUEeSaqCRuVK32aFcHablx3g7qzsYw',
    appId: '1:482407955732:web:5827938532fdb0538cd601',
    messagingSenderId: '482407955732',
    projectId: 'agapp-7983f',
    authDomain: 'agapp-7983f.firebaseapp.com',
    storageBucket: 'agapp-7983f.firebasestorage.app',
    measurementId: 'G-KPZV2EW84L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_qhNF5voCiglfwjVxaqz30RHD98_ELUs',
    appId: '1:482407955732:android:9fda45e8c351b4488cd601',
    messagingSenderId: '482407955732',
    projectId: 'agapp-7983f',
    storageBucket: 'agapp-7983f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC22OwkO0XGnBLCxH4Hulo7wKcpNJYxT8',
    appId: '1:482407955732:ios:8623b900e7c6bc838cd601',
    messagingSenderId: '482407955732',
    projectId: 'agapp-7983f',
    storageBucket: 'agapp-7983f.firebasestorage.app',
    iosBundleId: 'com.example.agapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC22OwkO0XGnBLCxH4Hulo7wKcpNJYxT8',
    appId: '1:482407955732:ios:8623b900e7c6bc838cd601',
    messagingSenderId: '482407955732',
    projectId: 'agapp-7983f',
    storageBucket: 'agapp-7983f.firebasestorage.app',
    iosBundleId: 'com.example.agapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-gUEeSaqCRuVK32aFcHablx3g7qzsYw',
    appId: '1:482407955732:web:67d6bdc4504b98808cd601',
    messagingSenderId: '482407955732',
    projectId: 'agapp-7983f',
    authDomain: 'agapp-7983f.firebaseapp.com',
    storageBucket: 'agapp-7983f.firebasestorage.app',
    measurementId: 'G-5D2TC943CL',
  );
}
